apiVersion: skaffold/v4beta13
kind: Config

metadata:
  name: v0

build:
  tagPolicy:
    sha256: {}

  artifacts:
    - image: template
      context: sandbox/template
      docker:
        dockerfile: dockerfile

    - image: agent
      context: sandbox/agent
      docker:
        dockerfile: dockerfile

    - image: sandbox
      context: sandbox/server
      docker:
        dockerfile: dockerfile

    - image: router
      context: sandbox/router
      docker:
        dockerfile: dockerfile

    - image: ai-orchestrator
      context: ai
      docker:
        dockerfile: dockerfile

    - image: auth
      context: auth
      docker:
        dockerfile: dockerfile

    - image: sync
      context: sandbox/sync-agent
      docker:
        dockerfile: dockerfile

manifests:
  rawYaml:
    - kubernetes/ai-deployment.yml
    - kubernetes/ai-service.yml
    - kubernetes/ingress.yml
    - kubernetes/rbac.yml
    - kubernetes/router-deployment.yml
    - kubernetes/router-service.yml
    - kubernetes/sandbox-server-deployment.yml
    - kubernetes/sandbox-server-service.yml
    - kubernetes/secrets.yml
    - kubernetes/auth-deployment.yml
    - kubernetes/auth-service.yml